### PR TITLE
Bundle DSL: handle names as frozen string literals

### PR DESCRIPTION
**Pull request by parkr**
I have a `Brewfile` like this:

```ruby
# frozen_string_literal: true

brew "rbenv"
brew "ruby-build"
```

When I run `brew bundle` or `brew bundle check`, I get:

```text
~/project#master$ brew bundle check
Error: Invalid Brewfile: can't modify frozen String
```

With `HOMEBREW_DEBUG=true`:

```text
~/project#master$ HOMEBREW_DEBUG=true brew bundle check
Error: Invalid Brewfile: can't modify frozen String
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:30:in `instance_eval'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:130:in `sanitize_tap_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:107:in `tap'
(eval):3:in `process'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:30:in `instance_eval'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:30:in `process'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:21:in `initialize'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/check.rb:46:in `new'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/check.rb:46:in `any_taps_to_tap?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/check.rb:16:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:61:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:78:in `exit'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:78:in `rescue in <top (required)>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:52:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

It's caused by calls to `downcase!` By applying this patch, I get:

```text
~/project#master$ brew bundle check
The Brewfile's dependencies are satisfied.
```

I'm not sure how to add a spec for this yet.

/cc @MikeMcQuaid

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Nice work @parkr!

> I'm not sure how to add a spec for this yet.

Could consider making the entire test suite run with disallowed mutable strings or have it `eval` a `Brewfile` somewhere with that header?

**Comment by parkr** [comment]
> Could consider making the entire test suite run with disallowed mutable strings

I can set `RUBYOPT="--enable-frozen-string-literal"` in `env` in the Travis configuration, or, perhaps, I can just set it for `bundle exec rake`. I'm not sure how Travis handles environment variables in `script`

Option 1:

```yaml
env:
  - RUBYOPT="--enable-frozen-string-literal"
```

Option 2:

```yaml
script:
  - brew style "$TRAVIS_REPO_SLUG"
  - RUBYOPT="--enable-frozen-string-literal" bundle exec rake
```

> have it eval a Brewfile somewhere with that header?

That is done by https://github.com/Homebrew/homebrew-bundle/pull/289/commits/4a7bff7f95aea0fe5dfd12acaea5daeaf91c60da.

**Comment by parkr** [comment]
I ran `RUBYOPT="--enable-frozen-string-literal" bundle exec rake` locally and it surfaces a number of other issues, including issues with RSpec (e.g. `$HOME/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/notifications.rb:319:in 'totals_line': can't modify frozen String (RuntimeError)`).

The better approach here is likely to use the `# frozen_string_literal: true` comment on each file.

**Comment by parkr** [comment]
@MikeMcQuaid Looks like CI is green. 💚

**Comment by MikeMcQuaid** [comment]
Thanks @parkr!

**Pull request merged**
