### PR TITLE
Remove `Brewfile.lock.json` generation.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This was originally added to faciliate later functionality from other maintainers that never materialized.

I've never heard anyone say this was useful and a lot of people have complained that it's useless or annoying.

I won't merge this immediately to give people a change to comment.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]
Makes sense. I've also never understood the purpose, so your explanation makes sense.

**Comment by colindean** [comment]
I have no objections. I've got a line for `Brewfile.lock.json` in every `.gitignore` in a repo with a `Brewfile`.

**Review by colindean — APPROVED** [review]

**Review by jacobbednarz — APPROVED** [review]

**Comment by jacobbednarz** [comment]
works for me!

**Comment by Brett-Best** [comment]
I actually found this helpful and had it committed to the repository.
It had a bunch of information about the environment in a last known working state which made finding where things broke a bit easier to debug.

It's not a big deal but perhaps it could default to not generating the lockfile and make it opt in only.

**Comment by Xe** [comment]
My CI relied on this for caching homebrew packages so they didn't have to be downloaded twice. Is there a way to re-enable spacebar heating?

**Comment by MikeMcQuaid** [comment]
Thanks for chiming in @georgettica @Xe! Can you elaborate on how you used/consumed this? Thanks!

**Comment by jasonkarns** [comment]
Was there a deprecation period for the `--no-lock` option? I have loads of scripts and applications whose bootstrap process uses `brew bundle --no-lock` that are all failing now with `Error: invalid option: --no-lock`.

**Comment by Xe** [comment]
> Thanks for chiming in @Xe! Can you elaborate on how you used/consumed this? Thanks!

GitHub actions. I wanted to avoid installing packages needlessly (this massively speeds up CI, you have no idea, it can save two digits of minutes per run) so I cache the /home/linuxbrew folder in GitHub Actions caches. Brewfile.lock.json changing means that the cache can be invalidated.

**Comment by MikeMcQuaid** [comment]
@Xe Thanks! Could you open an issue for that functionality (GitHub Actions caching) as I think it'd be valuable and may make more sense in Homebrew/brew.

**Pull request merged**
