### PR TITLE
Don't use reserved keywords

### PR DESCRIPTION
**Pull request by teoljungberg**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
There's merge conflicts to be resolved here.

**Comment by mikemcquaid** [comment]
Otherwise: :+1:

**Comment by teoljungberg** [comment]
@mikemcquaid This seems to already be fixed on master by `Pathname.new(filename).expand_path(Dir.pwd)`. Which means that if `filename` is a relative path, it will be expanded to `Dir.pwd`.

So the only relevant change is to rename the local variables to not use ruby keywords.

Do you want me to change this PR to reflect that, or close it entirely?

**Comment by mikemcquaid** [comment]
@teoljungberg Change the PR to reflect that, thanks.

**Comment by teoljungberg** [comment]
@mikemcquaid Rebased and updated

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
