### PR TITLE
bundle: use HOMEBREW_BREW_FILE

### PR DESCRIPTION
**Pull request by dawidd6**
`brew bundle` fails if `brew` binary is not present in directories present in PATH.
I just run into this issue while trying to execute `brew bundle` freshly after Homebrew installation.

### CODE REVIEW

**Review by Bo98 — APPROVED** [review]

**Comment by dawidd6** [comment]
Don't have access to merge in this repo. @Bo98 could you do the honors?

**Comment by Bo98** [comment]
Ah, yes. Of course!

**Comment by MikeMcQuaid** [comment]
Nice work @dawidd6!

**Review by pattystackzz3c — COMMENTED** [review]
PR

**Pull request merged**
