### PR TITLE
Add support for --global BREWFILE environment variable

### LINKED ISSUE #199: $BREWFILE environment variable
How about a `BREWFILE` environment variable as an alternative to `--file=`?

### PR DESCRIPTION
**Pull request by danielbayley**
Resolves #199.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Can you explain the use-case for this?

**Comment by danielbayley** [comment]
The same use case for `--global` (#60), only without the implication of having to further clutter the `HOME` directory, which some people (😉) find annoying… when tools hard code that path.

**Comment by MikeMcQuaid** [comment]
Where do you personally want to store this instead?

**Comment by danielbayley** [comment]
Personally, my `Brewfile` lives in my [local] `$DOTFILES` repo, which I put in `~/Library/Application Support/dotfiles` (macOS user)… I could go into the whole [_`XDG` spec_](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) thing, but I'm sure you would have likely come across issues about it before…

**Comment by MikeMcQuaid** [comment]
Ok. Will leave this open for a while to see if anyone else wants it as I'd rather wait and see if this would be used by more than just you.

> Personally, my Brewfile lives in my [local] $DOTFILES repo

Mine too, `~/.Brewfile` is just a symlink.

> I could go into the whole XDG spec thing, but I'm sure you would have likely come across issues about it before…

Do you set those variables yourself? Supporting them is an argument I'm more convinced by.

**Comment by danielbayley** [comment]
> Do you set those variables yourself? Supporting them is an argument I'm more convinced by.

I do have 
~~~ sh
setenv () { launchctl setenv $@ && export $1=${@:2}}

setenv XDG_DATA_HOME "$HOME/Library/Application Support"
setenv XDG_CONFIG_HOME $XDG_DATA_HOME
setenv XDG_CACHE_HOME ~/Library/Caches
~~~
in my `$ZDOTDIR/.zshenv`

Personally, I prefer to use environment variables that I can keep all in one place than relying on symlinks everywhere if I can…

**Comment by MikeMcQuaid** [comment]
@danielbayley Would you consider changing this PR to use the correct one of those instead? Thanks!

**Comment by danielbayley** [comment]
So you mean something like `$XDG_CONFIG_HOME/.Brewfile`? That's still semi-hardcoding the path and forces you to have `.Brewfile` [hidden] in the root of wherever that is (so in this case that would force it into `~/Library/Application Support/.Brewfile` which is even less “dotfiles” friendly…

Just `BREWFILE` I think is a lot more flexible and makes more sense.

I came across a similar issue here also https://github.com/MikeMcQuaid/strap/issues/21, and [this project](https://github.com/rcmdnk/homebrew-file), which appears to introduce `$HOMEBREW_BREWFILE` 😕.

**Comment by MikeMcQuaid** [comment]
> So you mean something like $XDG_CONFIG_HOME/.Brewfile?

Yes.

> Just BREWFILE I think is a lot more flexible and makes more sense.

I'm not convinced the flexibility is a good thing, I'm afraid.


> I came across a similar issue here also MikeMcQuaid/strap#21, and this project, which appears to introduce $HOMEBREW_BREWFILE 😕.

Perhaps that project is a better fit for your needs?

**Comment by MikeMcQuaid** [comment]
Passing on this for now but others please chime in if you desperately want this feature and come across this closed PR.

**Pull request closed without merging**
