### PR TITLE
Remove pre-2.6.0 logic.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Now that 2.6.0 has been released, this is no longer needed.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Should we give 2.6.0 some time to propagate in the wild before merging this?

**Review by jacobbednarz — APPROVED** [review]
👍 with a non-blocking question

**Review by colindean — APPROVED** [review]
Second the propagation time suggestion.

**Comment by Rylan12** [comment]
That shouldn't be a factor, I think. Users will get the updated `bundle` code by running `brew update` which will also update the brew code to 2.6.0, right?

**Comment by jacobbednarz** [comment]
As I understand it, providing they use `brew update` yes however, if they update individual taps/repositories somehow this could get murky. I'm 👍 to not worrying about those cases too much though as `brew update` should get them back on the right path if so 🙂

**Comment by MikeMcQuaid** [comment]
> Users will get the updated `bundle` code by running `brew update` which will also update the brew code to 2.6.0, right?

This.



> I'm 👍 to not worrying about those cases too much though as `brew update` should get them back on the right path if so 🙂

Agreed.

**Comment by fjarlq** [comment]
Commit 0839a47 results in this error during `brew bundle cleanup`:

    Error: Invalid usage: this command requires a formula or cask argument
    Warning: Failed to parse `brew info --cask --json=v2`:
    767: unexpected token at ''

I've submitted PR #836 to fix this.

**Pull request merged**
