### PR TITLE
Pluralize 'dependency' in bundle output

### PR DESCRIPTION
**Pull request by kjperry**
I apologize in advance for my pedantry

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Your pedantry is very much welcome, thanks! Unfortunately `rubocop` has responded with pedantry in kind and `brew style homebrew/bundle` is now failing. Can you fix that up? Thanks!

**Comment by MikeMcQuaid** [comment]
@kjperry Gentle ping on the comments.

**Comment by kjperry** [comment]
@MikeMcQuaid Whoops, this slipped my mind in a deluge of GitHub notifications, sorry! Should be good now.

**Comment by MikeMcQuaid** [comment]
Thanks for your first contribution to Homebrew/bundle, @kjperry! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
