### PR TITLE
Adds documentation about outputting to console

### PR DESCRIPTION
**Pull request by brunophilipe**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
👍 but needs `master` merged in first.

**Comment by mikemcquaid** [comment]
@brunophilipe Ping on this.

**Comment by MikeMcQuaid** [comment]
Thanks @brunophilipe! For future reference, we don't get notified on you adding commits so it's worth posting a wee comment just so I know to merge.

**Comment by brunophilipe** [comment]
👍 Sorry about that!

**Pull request merged**
