### PR TITLE
check homebrew revision against minimum requirement

### PR DESCRIPTION
**Pull request by xu-cheng**
cc @mikemcquaid

### CODE REVIEW

**Comment by xu-cheng** [comment]
Comments?

**Comment by mikemcquaid** [comment]
Seems good :+1:

**Comment by mikemcquaid** [comment]
This doesn't work with shallow clones of Homebrew, unfortunately.

**Comment by mikemcquaid** [comment]
(which our installer does by default now, I believe)

**Comment by xu-cheng** [comment]
You are right. I reverted this PR for now. I will consider the alternative solution. IMO, we may consider bump homebrew's version whenever its CLI API makes any change.

**Comment by mikemcquaid** [comment]
Could maybe go by the date of the latest commit in `origin/master` instead of the commit hash?

**Comment by xu-cheng** [comment]
I dunno. But aren't the date of commits in non-chronicle order? I mean sometimes we may push the commits authored a long time ago.

**Comment by mikemcquaid** [comment]
The authorship date may be old but the commit date will not. e.g. check `git log --pretty=fuller` and the `CommitDate`.

**Pull request merged**
