### PR TITLE
checker: fix handling `mas`.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
CC @jsatk

Fixes https://github.com/Homebrew/homebrew-bundle/issues/401

### CODE REVIEW

**Comment by jsatk** [comment]
Thank you so much @MikeMcQuaid. I really appreciate your time.

**Comment by jsatk** [comment]
@MikeMcQuaid any estimate on when this will land in the release version of bundle that ships with Homebrew?

**Comment by MikeMcQuaid** [comment]
It already is. ‘brew update’. Thanks for the kind words ❤️

**Comment by jsatk** [comment]
Ah.  I feel silly.  Thank you.

**Pull request merged**
